import React from 'react';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../../styles/auth/Register.module.scss';
import illustrationImg from '../../assets/images/illustration.svg';
import Button from '../../components/Button';

export default function Register() : JSX.Element {
  function registerUser() {
    console.log('Usuário deve ser registrado aqui');
  }

  return (
    <div className={styles.page}>
      <Head>
        <title>R$4You - Registre-se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside>
        <div className={styles.illustrationImg}>
          <Image src={illustrationImg} alt="Ilustração simbolizando perguntas e respostas" />
        </div>
        <strong>Cria salas de Q&amp;A ao-vivo</strong>
        <p>Tire as dúvidas da sua audiência em tempo-real</p>
      </aside>
      <main>
        <div className={styles.mainContent}>
          <form onSubmit={registerUser}>
            <label htmlFor="name">Nome</label>
            <input id="name" type="text" autoComplete="name" required />
            <label htmlFor="email">Email</label>
            <input id="email" type="email" required />
            <input id="email" type="email" required />
            <Button type="submit">Confirmar</Button>
          </form>
        </div>
      </main>
    </div>
  )
}