import React from 'react';
import Router from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { store } from 'react-notifications-component';
import styles from '../styles/Auth.module.scss';

import illustrationImg from '../assets/images/undraw_projections.svg';
import logoImg from '../assets/images/logo.svg';
import googleIconImg from '../assets/images/google-icon.svg';

import Button from '../components/Button';

import { useAppContext } from '../context/auth';

export default function Auth() : JSX.Element {
  const { user, signInWithGoogle } = useAppContext();

  async function handleRegisterEmail() {
    // Router.push('/auth/register');
  }

  async function handleLoginWithGoogle() {
    if(!user) {
      await signInWithGoogle().then(() => {
        Router.push('/');
      }).catch(() => {
        store.addNotification({
          title: "Não foi possível efetuar o login!",
          message: "Verifique suas credenciais Google.",
          type: "danger",
          insert: "top",
          container: "top-right",
          animationIn: ["animate__animated", "animate__fadeIn"],
          animationOut: ["animate__animated", "animate__fadeOut"],
          dismiss: {
            duration: 5000,
            onScreen: true
          }
        });
      });
    } else {
      Router.push('/');
    }
  }

  return (
    <div className={styles.page}>
      <Head>
        <title>R$4You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside>
        <strong>Está na hora de melhorar sua vida financeira</strong>
        <div className={styles.illustrationImg}>
          <Image src={illustrationImg} alt="Ilustração simbolizando perguntas e respostas" />
        </div>
        <p>Deixe que os $ons te ajudem a cuidar melhor do seu dinheiro, com suas projeções em tempo real.</p>
      </aside>
      <main>
        <div className={styles.mainContent}>
          {/* <Image src={logoImg} alt="R$4You" /> */}
          <div className={styles.buttons}>
            <button onClick={handleLoginWithGoogle} className={styles.buttonGoogle}>
              <div className={styles.logoGoogle}>
                <Image src={googleIconImg} alt="Logo do Google" />
              </div>
              Google
            </button>
            <Button onClick={handleRegisterEmail} type="submit">
              Registre-se com seu Email
            </Button>
          </div>
          <div className={styles.separator}>Já é registrado? Faça login</div>
        </div>
      </main>
    </div>
  )
}
