import React, { useEffect } from 'react';
import Router from 'next/router';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import illustrationImg from '../assets/images/illustration.svg'

export default function Home() : JSX.Element {
  useEffect(() => {
    Router.push('/auth');
  })

  return (
    <div className={styles.page}>
      <Head>
        <title>R$4You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside>
        <Image src={illustrationImg} alt="Ilustração simbolizando perguntas e respostas" />
        <strong>Cria salas de Q&amp;A ao-vivo</strong>
        <p>Tire as dúvidas da sua audiência em tempo-real</p>
      </aside>
      {/* <main>
        <div className={styles.mainContent}>
          <Image src={logoImg} alt="R$4You" />
          <button onClick={handleLoginWithGoogle} className={styles.createRoom}>
            <div className={styles.logoGoogle}>
              <Image src={googleIconImg} alt="Logo do Google" />
            </div>
            Crie sua sala com o Google
          </button>
          <div className={styles.separator}>ou entre em uma sala</div>
          <form>
            <input
              type="text"
              placeholder="Digite o código da sala"
            />
            <Button type="submit">
              Entrar na sala
            </Button>
          </form>
        </div>
      </main> */}
    </div>
  )
}
